// src/pages/AboutPage.jsx

import React from 'react'
import Navbar from '../components/Navbar'

const AboutPage = () => {
  return (
    <div className="flex min-h-screen items-center justify-center bg-lime-300 p-4">
      <div className="mx-auto flex w-full max-w-[1000px] flex-col">
        <Navbar />

        <h1 className="mt-8 text-center text-3xl font-bold">About This Application</h1>

        <div className="mx-auto mt-14 w-full max-w-[800px] border bg-white p-10 text-left shadow-[4px_4px_0_0_rgba(0,0,0,1)]">
       
          <div className="mt-6">
            <h2 className="text-2xl font-semibold mb-2">Our Mission</h2>
            <p>
              This application empowers users to understand their medicines better. By analyzing medicine images, the app extracts and summarizes essential information such as usage instructions, possible side effects, age recommendations, expiry details, and more—helping you make informed decisions about your health.
            </p>
          </div>

          <div className="mt-6">
            <h2 className="text-2xl font-semibold mb-2">How It Works</h2>
            <ul className="list-disc list-inside">
              <li>Upload or capture a photo of your medicine packaging or leaflet.</li>
              <li>Our AI processes the image, extracts relevant details, and presents a structured report.</li>
              <li>Review information including usage, side effects, storage, manufacturer, and more.</li>
            </ul>
          </div>

          <div className="mt-6">
            <h2 className="text-2xl font-semibold mb-2">Key Features</h2>
            <ul className="list-disc list-inside">
              <li>Easy-to-use interface for uploading medicine images.</li>
              <li>Comprehensive analysis covering all important aspects of the medicine.</li>
              <li>Clear warnings and prescription information.</li>
              <li>Disclaimer to always consult a healthcare professional for medical advice.</li>
            </ul>
          </div>

          <div className="mt-6">
            <h2 className="text-2xl font-semibold mb-2">Disclaimer</h2>
            <p>
              The information provided by this application is generated by artificial intelligence and is intended for informational purposes only. It is not a substitute for professional medical advice, diagnosis, or treatment. Always consult your doctor or another qualified health provider with any questions you may have regarding a medical condition.
            </p>
          </div>

          <div className="mt-6">
            <h2 className="text-2xl font-semibold mb-2">Contact & Feedback</h2>
            <p>
              We value your feedback! If you have suggestions, encounter issues, or want to get in touch, please use the contact form on our website or email us at <a href="mailto:yes20sh@outlook.com" className="text-blue-600 underline">yes20sh@outlook.com</a>.
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}

export default AboutPage
